import { Product, StoreProfile, UserAccount } from '../types';

export const DEFAULT_STORE_PROFILE: StoreProfile = {
  name: 'Mega Tehnik Elektronik',
  tagline: 'Solusi Elektronik, Terpercaya!',
  address: 'Blok Gebangmampang, Desa Margamulya, Kec. Bongas',
  phone: '0852-2429-7545',
  footerNote: 'Barang yang sudah dibeli tidak dapat ditukar/dikembalikan kecuali ada perjanjian.',
  paperSize: '58mm',
  showDateTime: true,
  showCashierName: true,
  cashierName: 'Kasir 01',
  autoSaveProducts: true,
  currency: 'Rp',
};

export const DEFAULT_USERS: UserAccount[] = [
  {
    id: 'user-admin',
    username: 'admin',
    password: 'admin123',
    name: 'Administrator',
    role: 'admin',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-kasir',
    username: 'kasir',
    password: 'kasir123',
    name: 'Kasir 01',
    role: 'kasir',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Kabel Eterna NYM 2 x 1.5 mm (Meter)',
    aliases: ['Kabel Putih', 'Kabel Kawat', 'Kabel NYM Putih', 'Kabel Listrik 2x1.5'],
    price: 9500,
    category: 'Kelistrikan',
    unit: 'Meter',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Mata Gerinda Potong WD 4" x 1.2mm',
    aliases: ['Batu Potong', 'Mata Gerinda Besi', 'Batu WD', 'Gerinda Tipis'],
    price: 4500,
    category: 'Perkakas',
    unit: 'Pcs',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Pipa PVC Rucika D 1/2 Inch (4 Meter)',
    aliases: ['Pipa Paralon 1/2', 'Pipa Air Putih', 'Paralon Rucika', 'Pralon Setengah'],
    price: 32000,
    category: 'Plumbing',
    unit: 'Batang',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'Kran Air Onda 1/2 Inch Kuningan',
    aliases: ['Kran Onda', 'Keran Tembok', 'Kran Besi', 'Keran Kuningan'],
    price: 38000,
    category: 'Plumbing',
    unit: 'Pcs',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    name: 'Lem Pipa PVC Isarplas 45 Gram',
    aliases: ['Lem Paralon', 'Lem Pralon', 'Isarplas Tube', 'Lem Pipa'],
    price: 7500,
    category: 'Bahan Perekat',
    unit: 'Tube',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    name: 'Obeng Plus Minus Bolak Balik Magnet',
    aliases: ['Obeng Bolak Balik', 'Obeng Dua Arah', 'Obeng Amerika', 'Obeng Plus Min'],
    price: 25000,
    category: 'Perkakas',
    unit: 'Pcs',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    name: 'Isolasi Listrik Unibell Hitam',
    aliases: ['Solasi Hitam', 'Selotip Listrik', 'Isolasi Kabel', 'Lakban Listrik'],
    price: 6000,
    category: 'Kelistrikan',
    unit: 'Rol',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-8',
    name: 'Semen Gresik 40 Kg',
    aliases: ['Semen Zak', 'Semen PC', 'Gresik 40kg'],
    price: 64000,
    category: 'Bahan Bangunan',
    unit: 'Zak',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
